### ISSUE TITLE
'Gramatically' should be 'grammatically'

### ISSUE THREAD

**Issue by pivic** [Debdut/uuid-readable#1]
If I'm picky—and I am—there are some issues with the current linguistic state of **README.md**:

> Generate Easy to Remember, Readable UUIDs, that are Shakespearean gramatically correct sentences

There are a few errors in that line; To clarify matters, it could be written like this instead:

* Generate easy-to-remember and readable UUIDs that look like Shakespeare would have written them.

There is no 'Shakespearean grammar'; English has always been a mishmash of different styles and rules and still is, as opposed to languages like French, which is decided by a committee since centuries ago. As such, Shakespeare didn't set any grammar rules, but actually rather broke them. Even if this is the intended meaning in your text, the sentiment is sadly lost due to the altogether poor readability of README.md.

> Has a Shakespeare feeling

This is not wrong, but differs in consistency from what you have written elsewhere; You first wrote 'Shakespearean gramatically correct sentences', and line differs from the previous one, which lacks in readability and might vex readers.

There are some [[compound-modifier]]((https://en.wikipedia.org/wiki/Hyphen#Compound_modifiers)) issues here as well.

**Comment by Debdut** [comment]
Fixed, 😊
