### ISSUE TITLE
uuid v9

### ISSUE THREAD

**Issue by katerineknox** [Debdut/uuid-readable#12]
Hello,

Thanks for the library. I was wondering if there was any appetite for updating the `uuid` version to v9? Or having `uuid` specified as a peer dependency that would support v8 and v9.

UUID Changelog here: https://github.com/uuidjs/uuid/blob/main/CHANGELOG.md

The breaking changes are mainly around dropping support for legacy browsers and node versions so I don't believe upgrading would require any code changes. Would be happy to raise a PR if there are no objections to upgrading?

**Comment by Debdut** [comment]
Yes, please PR!

**Comment by katerineknox** [comment]
PR raised here: https://github.com/Debdut/uuid-readable/pull/13. Weirdly don't appear able to add reviewers to the PR.

**Comment by Debdut** [comment]
merged!

Debdut Karmakar
calendly.com/debdut
@KarmakarDebdut <https://twitter.com/KarmakarDebdut>
Github <https://github.com/debdut>
ProductHunt ***@***.***>
